package top.duwd.fintech.common.mapper.sub;

import tk.mybatis.mapper.common.Mapper;
import top.duwd.fintech.common.domain.sub.entity.SubQuestionDetailEntity;

public interface SubQuestionDetailEntityMapper extends Mapper<SubQuestionDetailEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_question_detail
     *
     * @mbggenerated Mon May 04 20:44:48 CST 2020
     */
    SubQuestionDetailEntity selectByPrimaryKey(Integer id);

}